server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
zuul:
  SendErrorFilter:
    post:
      disable: true
  ignoredServices: '*'
  ignoredPatterns: '/api/v1/*/internal/**'
  sensitive-headers: Cookie,Set-Cookie
  routes:
    user: /api/v1/user/**
    subscription: /api/v1/subscription/**
    post: /api/v1/post/**
    view: /api/v1/view/**
    auth: /api/v1/auth/**

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
          timeoutInMilliseconds: 100000

ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000